version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: quarkus-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quarkus
      MONGO_INITDB_ROOT_PASSWORD: quarkus
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  postgres-data:
  mongodb-data: 