-- Cognito + colunas usadas pelo código atual (idempotente no Neon)

ALTER TABLE users ADD COLUMN IF NOT EXISTS cognito_sub VARCHAR(128);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'USER';

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_cognito_sub ON users (cognito_sub) WHERE cognito_sub IS NOT NULL;

ALTER TABLE trip_segments ADD COLUMN IF NOT EXISTS daily_cost NUMERIC(10, 2);

ALTER TABLE activities ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE meals ADD COLUMN IF NOT EXISTS restaurant_name VARCHAR(255);
ALTER TABLE meals ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_status VARCHAR(20);
